# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
# highlighter:      rouge # for local testing
highlighter:      rouge # for github.io deployment
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        /blog/:year-:month-:day/:title.html
# relative_permalinks: true

# Setup
title:            'Media Theory/ Media Practice'
tagline:          'ENG 7006, Winter 2015'
description:      'ENG 7006, Winter 2015'
url:              http://eng7006.github.io
baseurl:          /

author:
  name:           'Scott C. Richmond'
  url:            http://kredati.org

# paginate:         5
# paginate_path:    "/blog/page:num/"


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
